### ISSUE TITLE
When running an experiment after changing the image size only , the experiment fails with a tensor size mismatch error

### ISSUE THREAD

**Issue by p4rallax** [luminide/example-gi-tract#1]
I ran an experiment with a different image size than 320 , and the experiment failed. 
The exact same code ran perfectly when I changed the size back to 320. There is some dependency on image size but I was not able to find anything. Will make a PR if I find it!
Here is the log-

Running on cuda
34387 examples in training set
3821 examples in validation set
Training in progress...
Epoch 0:
Traceback (most recent call last):
  File "../code/train.py", line 280, in <module>
    main()
  File "../code/train.py", line 276, in main
    trainer.fit(args.epochs)
  File "../code/train.py", line 143, in fit
    train_loss = self.train_epoch(epoch)
  File "../code/train.py", line 211, in train_epoch
    outputs = model(images)
  File "/home/ubuntu/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/vol_b/test/code/models.py", line 24, in forward
    x = self.model(x)
  File "/home/ubuntu/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/env/lib/python3.8/site-packages/segmentation_models_pytorch/base/model.py", line 16, in forward
    decoder_output = self.decoder(*features)
  File "/home/ubuntu/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/env/lib/python3.8/site-packages/segmentation_models_pytorch/fpn/decoder.py", line 111, in forward
    p4 = self.p4(p5, c4)
  File "/home/ubuntu/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/env/lib/python3.8/site-packages/segmentation_models_pytorch/fpn/decoder.py", line 33, in forward
    x = x + skip
RuntimeError: The size of tensor a (20) must match the size of tensor b (21) at non-singleton dimension 3

**Comment by anlthms** [comment]
Yes, I ran into the same error with other image sizes. With some image sizes, the FPN decoder produces feature maps with odd-valued height and width, which do not match with interpolated maps. Please do make a PR if you find a solution.

**Comment by p4rallax** [comment]
I digged in a little , and it seems that the decoder wants the image size to be a multiple of 32. Same with Unet.  Using any image size which was a multiple of 32 worked fine.
